language: node_js
node_js:
- node
- lts/*

cache:
    directories:
    - node_modules # NPM packages

# command to install dependencies
install: yarn

# command to run tests
script :  yarn test:ci && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js